vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
            product_image:
                uri_prefix: /images/products
                upload_destination: '%kernel.project_dir%/public/images/products'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            page_image:
                uri_prefix: /images/pages
                upload_destination: '%kernel.project_dir%/public/images/pages'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer